use crate::parser::{value::Value, Memory};

#[derive(Debug, Clone)]
pub enum Instruction {
    Deref(Value, Memory),
    DerefAssign(Value, usize, Value),
    While(Value),
    EndWhile(Value),
    If(Value, usize, bool),
    Else(usize),
    EndIf(usize, bool),
    TernaryIf(Value, Value, Value, Memory),
    Copy(Value, Memory),
    Clear(Memory, Memory),
    Input(Memory),
    Add(Value, Value, Memory),
    Sub(Value, Value, Memory),
    Mul(Value, Value, Memory),
    Div(Value, Value, Memory),
    Mod(Value, Value, Memory),
    Neg(Value, Memory),
    Out(Value),
    Eq(Value, Value, Memory),
    Neq(Value, Value, Memory),
    Lt(Value, Value, Memory),
    Le(Value, Value, Memory),
    Gt(Value, Value, Memory),
    Ge(Value, Value, Memory),
    Inc(Value),
    Dec(Value),
    Shl(Value, Value, Memory),
    Shr(Value, Value, Memory),
    And(Value, Value, Memory),
    Or(Value, Value, Memory),
    Not(Value, Memory),
    Xor(Value, Value, Memory),
}
